language: node_js
node_js:
  - "5"

install:
  - npm install

script:
  - npm run build

branches:
  only:
    - master

deploy:
  provider: s3
  access_key_id:
    secure: "awNy9Vq0J+OOXjCx9xx490xEAE+MAfVyK5lrhJAMfw8DOyZZf3E3Da/njPS2XH6PITQGWlbUgMTslo/oXZ90t1i3xGZvbO8R6gV0i+oZGoJJ36El/EM67tNG3C6GXj6HwqLuiJRTooGo7Q3FdrSoYtGVh8Iq3VBP4RCvxvuhgz3SboQT2ZKT/Qeg2GjpBS88jJEvoHzM/opir/qCbtFPJCZX967dsN49IKeXze4DESeCyW1q52i1dZXybWXdnICTByIG9MnPxNlrVTOT2AbNxmW7Qe34Cgtl26637nsg8WDCUX1TWmZPRPZrvXPpMXeFulQgfNp/n59X08argyFfdSmvQr9hKo1XswwcpVAinr68OcBF250QaCoEneZdTUvXe8dWYm9OHEyRnovaE5rVJkuQ9Izy8iDnbW/fH4qr40cEMGwrNOtbj3JhF1qoM48+VWPtVRXLM942dm/xPUVtgsiYA9VAVCsZ/YIa91CYEdJYYqbdk6DXA75ZSmrtkf0VAcECJgZtSYvvaUqxUWdbAXotzKVwEzKBR12Q42Lcf//12Jkndm/YSbmR5X2l8eA8aHIim9WUpanxF76vJaAZdpYTKG5CwrMummp+EejG2zmVAkwUDLw2SoX4JWCFPWiqsqAzdcIFdCWWjUojgdmC8GaLgWlvrWFaXmZAwFX+vEU="
  secret_access_key:
    secure: "Wm0NXRIa+c9SDVTUcxILce5+2bJEAvSwwGZo92EBeSbNOCUtS1zahmpZlFZdueKmfdheDk07vNedMcaSdeY2oIiNzZYiXRiGXNtijrAWoPhhlibaou1ZP3uM5lmVQg/eOqfURzNY9CdePaN4nPI39f6+mydO4G548NvqJr4gZpTh3X6/ixpYCuCtPB3HP+myEgIx3egLyMb8xXax+xebc1Q0X+xYLd9wSKKbRGsJTntqgNOvUZ/Mzb5KVLD91FGzHtBoVW6XK5ZbI5eq8Vbrd9fvXQHBY3BeExwcTG9Gk1cmoMJVLOWPlNhJblfIWn1U4q90mJfFCmPz756378qARLVNQ00rgvOHmLm9eIfyt7JZZfqdvWZIaRV8FzoH7qIiVKbwAPZ42YCLA6x+Imiay9BlNoBX3ScHQHGQieyWYBLGtAiAbSgFOgD5Kq+7hlUoRmyEgx42tMWqm+7g8+uRIO++EbeV6DPr6kh0zuL0ID7TvI5XdRarjyEXCq/uPgaym0+i38TqtDfBpJlIKMYADq2Cczwra/oeXhLiEGFicLz4bDHo0FtQlgvUL7QnewIkt98VYuAM7aaak87OU3fLE6JO4uKauRxe/AG+DjGHXR3JJF63hMjPYnJrTzDEbb5UUoyUY2i1S/+zQva/rFcoqiRAulGt7brT6OD94w2f9w0="
  bucket: "asaservice.space"
  skip_cleanup: true
  region: "eu-west-1"
  local_dir: build
