language: node_js
node_js:
  - "5"

install:
  - npm install

script:
  - npm run build

branches:
  only:
    - master

deploy:
  provider: s3
  access_key_id:
    secure: "lbRHt4mYDF+Ut6CwyefE6D9obPBA/LL795ujyxBEXjmq8nFOqxtADJAkDfWFb6vsWIf2K0oSI1QNZ7qLJVS36bbSn5K7zTVwH/dq9j0OKxc1TKYImkPtvZ38O7/9mTesfPA+6CVr2Mu10qMzE+FZWhoRx/H8wm0WKf+H3W38LHPPNNyAKxmpiiTgEZowFkavBwFawxvZ9GFl/KiaxwdlX3N8sxucBTSHkXKyqf8bHUQdr415w5tPyOmia12n8LL8WMryUnWqQs+hsAlElnLTZvSshotqc0SuTQenp8IRqluZBd0yC/erPOFWjW8AO8NVeB8LnC9SRzIdcLozPvMQfEWjqGXWtSiLsec3M7bP8haF4+pEiMJdUcHNtoL8Ebx1oxM8PLsUtnwi5Vefap6nl5ASVWXFqdmTDsACbD/tzFXeV/MajdB73AaDF5tGduEZhqiNpagUbUCjI0D0JklyTEoPH4eyFxgH9o2W5SBu88hRj0ZTa9zH9SrlcNAtPPPRIe5VCAbGdrA+cjrLx/9sAPQGw28J7K8PStzSNvKZ/W1uNcXOL4VANexWrecOXhZSL8cwD7ZgkcBxykGqwu0plg+wi5Rwz9N7awXRr8fKwfMLeoibmoKOI8RFWd35BxJAkuXmOsets+P35+4WYscDw7Qrq6wFi1ssUo3UgnnRrXo="
  secret_access_key:
    secure: "nzOXia0LnNSBddMP3iR7T/LTQQZSrujTfkaMafkI9gM3RWon2oAtUpo8RAUP/OpWC6F1grmV2iX9jSRJ1V199Q3cll7+EuvR/ksvFRYZK70ncvbF8wOYHmEKMI74wSHUT0K9awSdAzni5clf1xWtI8JBscljRDHPnQ/iP0Wwkdw+2Yg5nLZGt+u0DiycUC68/tI93WC/9dTYmSW58VsdwghHFYCIljS6rrNInd3gAH/QW/4L0wyS9yv8XUG22gkXXRzPfeQGsnoy7kGNPak1/crrFuDypTp//uCOlFlkbBXqTTrDsDb6crk+yh6fxcmfoSt9Vh9aNzTpNpmQJy+vVpgSAhNGTwfc6nCSunVrH8zbF/C56/q+4aS+2984J6Tyk38tCAo0m+brSUrozC+owTsRfOGpdrST4nnpctGOqfjC1+VyPO3Oj+3VIV91jm8FxEBTF1WHl0YjmNzAyK3rHEZe4Bb1KWk8F/9bnguDMq3TDMh8zCdfZzjqINsXY/8fATaB8XsjyHC/R/mSuZG96XZymVAVCAm6icgPvDBoTVJvsI3ngmgfu0tQ1AWF04P606eUBkoftarIzhlHjIiwNciAbpQ8Us+2vniKh0BLFw8wmZDrArLiMXEBudeVOSlskfFvBpi+tiody1k0Ff5NCqta4N7h4+ussDfoBk5RWuw="
  bucket: "asaservice.space"
  skip_cleanup: true
  region: "eu-west-1"
  local_dir: build
